import type { Metadata } from "next";
import "./globals.css";
import Logo from '@/components/Logo'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className='p-8'>
            <header className="flex justify-between items-center">
                <Logo/>
            </header>
            {children}
        </body>
    </html>
  );
}
